### PR TITLE
Added offsets

### PR DESCRIPTION
**Pull request by ecvelayo**

### CODE REVIEW

**Review by keyrwinz — CHANGES_REQUESTED** [review]
@ecvelayo sir ean pwdi ko pa change sa offset for getCategories na function sa line 100
old:
(isset($request['offset'])) ? $this->model->offset($request['offset']) : null;
to:
(isset($request['offset'])) ? $this->model = $this->model->offset($request['offset']) : null;

thanks!

**Comment by kennCK** [comment]
@ecvelayo  @keyrwinz  please bagud ko change ani

**Comment by keyrwinz** [comment]
> @ecvelayo sir ean pwdi ko pa change sa offset for getCategories na function sa line 100
> old:
> (isset($request['offset'])) ? $this->model->offset($request['offset']) : null;
> to:
> (isset($request['offset'])) ? $this->model = $this->model->offset($request['offset']) : null;
> 
> thanks!

DONE!

**Comment by ecvelayo** [comment]
giusab na nako sir

**Pull request merged**
