### PR TITLE
Prep time added

### PR DESCRIPTION
**Pull request by ecvelayo**

### CODE REVIEW

**Comment by kennCK** [comment]
@ecvelayo unsay ni ang PayloadController?

**Comment by ecvelayo** [comment]
@kennCK giremove na nako sir katong gipabalhin gani si payloads sa common.

**Comment by kennCK** [comment]
@ecvelayo let's have code review nya ani sir. Thank you

**Comment by ecvelayo** [comment]
cge sir

**Comment by kennCK** [comment]
@ecvelayo 3 PM is good sir. Thank you

**Pull request merged**
