### PR TITLE
shops offset limit and join statement updated

### PR DESCRIPTION
**Pull request by ecvelayo**

### CODE REVIEW

**Comment by kennCK** [comment]
@ecvelayo let's have review ani

**Comment by kennCK** [comment]
@ecvelayo scenario sir mo limit sya daan? but what will happen if ang sa limit kay not within the radius?

**Comment by ecvelayo** [comment]
dba limited within 30km ang shops ireturn? if lapas 30km d sya iapil sa return

**Comment by kennCK** [comment]
image

The issue sir kay on your retrieve kay ni limit na sya but since i validate pa ang locations within specified radius. let see sa limit naka get ka ug 30 merchants but and within the radius kay wlay within so expected  empty ang return.

**Comment by ecvelayo** [comment]
ah i see sir. pwede ang limit nato adto sa for loop sad nga if mao na ang counter ug limit values, break na sya. oks rana?

**Comment by kennCK** [comment]
recommendation sir is to get all merchant using same scope. then from the scope kay filter within the radius. Since we can get region and locality on user location.

**Comment by kennCK** [comment]
then from results adto na i filter and limit.

**Comment by ecvelayo** [comment]
so ipass sad si scope together with longitude and latitude sir?

**Comment by kennCK** [comment]
better sir or determine the scope sa backend na.

**Comment by ecvelayo** [comment]
cge try nako na ang determine through backend based sa long lat sir. iclose sa ni nako until then.

**Comment by kennCK** [comment]
solution sir kay mo get ka ug isa sa then from isa kay i retrieve nimo tanang merchants using ato na scope then from that kay check radius.

**Comment by ecvelayo** [comment]
copy sir ako iimplement rn

**Pull request closed without merging**
